# Generated by Django 2.2.4 on 2020-04-03 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text_long',
            new_name='question_desc',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='views',
            new_name='question_votes',
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=10),
        ),
    ]
